# Figure generation for "Dissolving the Annuity Puzzle"
#
# Produces 5 publication-quality figures:
#   1. Sequential decomposition bar chart
#   2. Gamma sensitivity curve
#   3. Hazard multiplier sensitivity
#   4. Policy function (optimal alpha by wealth)
#   5. CEV heatmap
#
# Run: julia --project=. scripts/generate_figures.jl

using Plots
using DelimitedFiles
using Printf

include(joinpath(@__DIR__, "..", "src", "AnnuityPuzzle.jl"))
using .AnnuityPuzzle

# Output directories
const FIG_PDF = joinpath(@__DIR__, "..", "figures", "pdf")
const FIG_PNG = joinpath(@__DIR__, "..", "figures", "png")
mkpath(FIG_PDF)
mkpath(FIG_PNG)

# Plots defaults: serif font, thick lines, no title
default(
    fontfamily = "Computer Modern",
    titlefontsize = 12,
    guidefontsize = 11,
    tickfontsize = 10,
    legendfontsize = 9,
    linewidth = 1.5,
    framestyle = :box,
    grid = true,
    gridalpha = 0.2,
    dpi = 300,
)

# Colorblind-friendly palette (Okabe-Ito)
const CB_BLUE   = RGB(0.0/255, 114.0/255, 178.0/255)
const CB_ORANGE = RGB(230.0/255, 159.0/255, 0.0/255)
const CB_GREEN  = RGB(0.0/255, 158.0/255, 115.0/255)
const CB_RED    = RGB(213.0/255, 94.0/255, 0.0/255)
const CB_PURPLE = RGB(204.0/255, 121.0/255, 167.0/255)
const CB_CYAN   = RGB(86.0/255, 180.0/255, 233.0/255)
const CB_YELLOW = RGB(240.0/255, 228.0/255, 66.0/255)
const CB_BLACK  = RGB(0.0/255, 0.0/255, 0.0/255)

function savefig_both(p, name)
    savefig(p, joinpath(FIG_PDF, name * ".pdf"))
    savefig(p, joinpath(FIG_PNG, name * ".png"))
    println("  Saved: $name.pdf, $name.png")
end

# =====================================================================
# Figure 1: Sequential Decomposition Bar Chart
# =====================================================================
function figure_1_decomposition()
    println("Generating Figure 1: Sequential Decomposition...")

    # Read decomposition results from CSV (generated by run_decomposition.jl)
    csv_path = joinpath(@__DIR__, "..", "tables", "csv", "decomposition.csv")
    if isfile(csv_path)
        raw = readdlm(csv_path, ',', Any; skipstart=1)
        step_labels = String[]
        step_ownership = Float64[]
        for i in 1:size(raw, 1)
            push!(step_labels, strip(string(raw[i, 1])))
            push!(step_ownership, Float64(raw[i, 2]))
        end
    else
        println("  WARNING: $csv_path not found, using placeholder values.")
        println("  Run scripts/run_decomposition.jl first to generate CSV.")
        step_labels = [
            "Yaari benchmark",
            "+ Social Security",
            "+ Bequests",
            "+ Medical risk",
            "+ Health-mortality corr. (R-S)",
            "+ Survival pessimism",
            "+ Pricing loads (MWR = 0.82)",
            "+ Inflation erosion (2%)",
        ]
        step_ownership = [56.2, 100.0, 100.0, 100.0, 89.0, 83.6, 18.6, 3.2]
    end

    n = length(step_labels)
    # Gradient from blue (Yaari) to red (full model), sized dynamically
    step_colors = [RGB(
        0.20 + 0.65 * (i - 1) / max(n - 1, 1),
        0.40 - 0.25 * (i - 1) / max(n - 1, 1),
        0.75 - 0.60 * (i - 1) / max(n - 1, 1),
    ) for i in 1:n]

    # Reverse so Yaari is at top (highest bar position)
    disp_labels = reverse(step_labels)
    disp_vals = reverse(step_ownership)
    disp_colors = reverse(step_colors)

    p = bar(
        1:n,
        disp_vals,
        orientation = :h,
        color = disp_colors,
        legend = false,
        xlims = (0, 108),
        ylims = (0.3, n + 0.7),
        yticks = (1:n, disp_labels),
        xlabel = "Predicted Ownership (%)",
        left_margin = 18Plots.mm,
        bottom_margin = 5Plots.mm,
        top_margin = 3Plots.mm,
        right_margin = 5Plots.mm,
        size = (700, 400),
        bar_width = 0.6,
    )

    # Observed benchmark line
    vline!([3.6], color = CB_BLACK, linestyle = :dash, linewidth = 1.2, label = "")
    annotate!(8.0, n + 0.45, Plots.text("Observed: 3.6%", 8, :left))

    # Value labels on bars
    for (i, val) in enumerate(disp_vals)
        x_pos = val < 10 ? val + 3.0 : val - 6.0
        txt_color = val < 10 ? :black : :white
        annotate!(x_pos, i, Plots.text(@sprintf("%.1f%%", val), 8, txt_color, :center))
    end

    savefig_both(p, "fig1_decomposition")
    return p
end


# =====================================================================
# Figure 2: Gamma Sensitivity Curve
# =====================================================================
function figure_2_gamma_sensitivity()
    println("Generating Figure 2: Gamma Sensitivity...")

    # Parse robustness CSV
    csv_path = joinpath(@__DIR__, "..", "tables", "csv", "robustness_full.csv")
    raw = readdlm(csv_path, ',', Any; skipstart=1)

    gamma_vals = Float64[]
    ownership_vals = Float64[]
    for i in 1:size(raw, 1)
        cat = strip(string(raw[i, 1]))
        cat != "Gamma sweep" && continue
        spec = strip(string(raw[i, 2]))
        # Parse gamma value from "gamma=X.XX"
        m = match(r"gamma=(\d+\.?\d*)", spec)
        m === nothing && continue
        g = parse(Float64, m.captures[1])
        # Parse ownership (handles both "X.X%" and bare "X.X")
        own_str = strip(replace(string(raw[i, 3]), "%" => ""))
        own = tryparse(Float64, own_str)
        own === nothing && continue
        push!(gamma_vals, g)
        push!(ownership_vals, own)
    end

    # Sort by gamma
    ord = sortperm(gamma_vals)
    gamma_vals = gamma_vals[ord]
    ownership_vals = ownership_vals[ord]

    p = plot(
        gamma_vals, ownership_vals,
        color = CB_BLUE,
        linewidth = 2.0,
        marker = :circle,
        markersize = 4,
        markercolor = CB_BLUE,
        markerstrokewidth = 0,
        legend = :topleft,
        label = "Full model",
        xlabel = "Risk Aversion (γ)",
        ylabel = "Predicted Ownership (%)",
        xlims = (1.3, 5.2),
        ylims = (-2, 45),
        size = (500, 340),
        left_margin = 5Plots.mm,
        bottom_margin = 5Plots.mm,
        top_margin = 3Plots.mm,
        right_margin = 3Plots.mm,
    )

    # Observed range band (3-6%)
    hspan!([3.0, 6.0], color = CB_GREEN, alpha = 0.18, label = "Observed range (3-6%)")

    # Mark baseline gamma = 2.5
    vline!([2.5], color = CB_RED, linestyle = :dash, linewidth = 1.0, label = "")
    annotate!(2.55, 38, Plots.text("γ = 2.5\n(baseline)", 8, :left, CB_RED))

    savefig_both(p, "fig2_gamma_sensitivity")
    return p
end


# =====================================================================
# Figure 3: Hazard Multiplier Sensitivity
# =====================================================================
function figure_3_hazard_sensitivity()
    println("Generating Figure 3: Hazard Multiplier Sensitivity...")

    # Read from robustness CSV
    csv_path = joinpath(@__DIR__, "..", "tables", "csv", "robustness_full.csv")
    labels = String[]
    ownership = Float64[]

    if isfile(csv_path)
        raw = readdlm(csv_path, ',', Any; skipstart=1)
        for i in 1:size(raw, 1)
            cat = strip(string(raw[i, 1]))
            cat != "Hazard mult" && continue
            spec = strip(string(raw[i, 2]))
            own_str = strip(replace(string(raw[i, 3]), "%" => ""))
            own = tryparse(Float64, own_str)
            own === nothing && continue
            push!(labels, replace(spec, r"\(.*\)" => s"\n\0"))
            push!(ownership, own)
        end
    end

    if isempty(labels)
        println("  WARNING: Hazard mult data not found in CSV, using placeholders.")
        labels = [
            "R-S functional\n[0.45, 1.0, 3.5]",
            "Baseline\n[0.50, 1.0, 3.0]",
            "HRS SRH\n[0.57, 1.0, 2.7]",
            "Conservative\n[0.60, 1.0, 2.0]",
        ]
        ownership = [0.0, 1.4, 5.7, 24.4]
    end

    bar_colors = [CB_BLUE, CB_GREEN, CB_ORANGE, CB_RED]
    n_bars = length(labels)
    if n_bars > length(bar_colors)
        bar_colors = repeat([CB_BLUE], n_bars)
    else
        bar_colors = bar_colors[1:n_bars]
    end

    p = bar(
        1:n_bars, ownership,
        color = bar_colors,
        legend = false,
        xticks = (1:n_bars, labels),
        ylabel = "Predicted Ownership (%)",
        xlabel = "Hazard Multiplier Specification [Good, Fair, Poor]",
        ylims = (0, 30),
        size = (560, 340),
        bar_width = 0.6,
        left_margin = 5Plots.mm,
        bottom_margin = 12Plots.mm,
        top_margin = 3Plots.mm,
        right_margin = 3Plots.mm,
        xrotation = 0,
    )

    # Observed range band
    hspan!([3.0, 6.0], color = CB_GREEN, alpha = 0.15, label = "")
    annotate!(3.85, 5.5, Plots.text("Observed (3-6%)", 8, :right, :darkgreen))

    # Value labels above bars
    for (i, val) in enumerate(ownership)
        annotate!(i, val + 1.0, Plots.text(@sprintf("%.1f%%", val), 9, :center))
    end

    savefig_both(p, "fig3_hazard_sensitivity")
    return p
end


# =====================================================================
# Figure 4: Policy Function -- Optimal Alpha by Wealth
# =====================================================================
function figure_4_policy_functions()
    println("Generating Figure 4: Policy Functions (requires model solves)...")

    # Calibration matching production runs
    AGE_START  = 65
    AGE_END    = 110
    GAMMA      = 2.5
    BETA       = 0.97
    R_RATE     = 0.02
    C_FLOOR    = 6_180.0
    W_MAX      = 3_000_000.0
    N_WEALTH   = 80
    N_ANNUITY  = 30
    N_ALPHA    = 101
    A_GRID_POW = 3.0
    N_QUAD      = 9
    MWR_LOADED = 0.82
    FIXED_COST = 1_000.0
    INFLATION  = 0.02
    THETA_DFJ  = 56.96
    KAPPA_DFJ  = 272_628.0
    # Use Lockwood's original theta at all gamma values (no recalibration)
    HAZARD_MULT = [0.50, 1.0, 3.0]

    grid_kw = (
        n_wealth = N_WEALTH, n_annuity = N_ANNUITY, n_alpha = N_ALPHA,
        W_max = W_MAX, age_start = AGE_START, age_end = AGE_END,
        annuity_grid_power = A_GRID_POW,
    )
    common_kw = (
        gamma = GAMMA, beta = BETA, r = R_RATE,
        stochastic_health = true, n_health_states = 3, n_quad = N_QUAD,
        c_floor = C_FLOOR, hazard_mult = HAZARD_MULT,
        survival_pessimism = 0.981,  # O'Dea & Sturrock (2023)
    )

    _ss_mean_val = sum(SS_QUARTILE_LEVELS) / length(SS_QUARTILE_LEVELS)
    ss_mean(age, p) = _ss_mean_val

    # Survival probabilities
    p_base = ModelParams(age_start = AGE_START, age_end = AGE_END)
    base_surv = build_lockwood_survival(p_base)

    # Payout rates
    p_fair = ModelParams(; gamma = GAMMA, beta = BETA, r = R_RATE, mwr = 1.0, grid_kw...)
    fair_pr = compute_payout_rate(p_fair, base_surv)
    grids = build_grids(p_fair, fair_pr)
    loaded_pr = MWR_LOADED * fair_pr

    # --- Panel A: No bequests, loads + inflation only ---
    println("  Panel A: solving (no bequests, loads + inflation)...")
    t0 = time()
    p_A = ModelParams(; common_kw...,
        theta = 0.0, kappa = 0.0,
        mwr = MWR_LOADED, fixed_cost = FIXED_COST, inflation_rate = INFLATION,
        medical_enabled = false, health_mortality_corr = false,
        grid_kw...,
    )
    sol_A = solve_lifecycle_health(p_A, grids, base_surv, ss_mean)
    alpha_A, _ = solve_annuitization_health(sol_A, loaded_pr; initial_health = 1)
    @printf("    Solved in %.1fs\n", time() - t0)

    # --- Panel B: Full model (DFJ bequests + R-S + loads + inflation) ---
    println("  Panel B: solving (full model)...")
    t0 = time()
    p_B = ModelParams(; common_kw...,
        theta = THETA_DFJ, kappa = KAPPA_DFJ,
        mwr = MWR_LOADED, fixed_cost = FIXED_COST, inflation_rate = INFLATION,
        medical_enabled = true, health_mortality_corr = true,
        grid_kw...,
    )
    sol_B = solve_lifecycle_health(p_B, grids, base_surv, ss_mean)
    alpha_B, _ = solve_annuitization_health(sol_B, loaded_pr; initial_health = 1)
    @printf("    Solved in %.1fs\n", time() - t0)

    W_grid = grids.W

    # Convert to thousands for x-axis
    W_k = W_grid ./ 1000.0

    # Filter to W <= $1M for display
    mask = W_grid .<= 1_000_000.0
    W_disp = W_k[mask]
    alpha_A_disp = alpha_A[mask]
    alpha_B_disp = alpha_B[mask]

    p1 = plot(
        W_disp, alpha_A_disp,
        color = CB_BLUE,
        linewidth = 2.0,
        xlabel = "Initial Wealth (\$000s)",
        ylabel = "Optimal Annuity Fraction (α*)",
        ylims = (-0.02, 1.02),
        xlims = (0, 1050),
        label = "",
        size = (460, 300),
        left_margin = 5Plots.mm,
        bottom_margin = 5Plots.mm,
        top_margin = 5Plots.mm,
        right_margin = 3Plots.mm,
    )
    annotate!(500, 0.92, Plots.text("(a) No bequests, no health risk", 9, :center))

    p2 = plot(
        W_disp, alpha_B_disp,
        color = CB_RED,
        linewidth = 2.0,
        xlabel = "Initial Wealth (\$000s)",
        ylabel = "Optimal Annuity Fraction (α*)",
        ylims = (-0.02, 1.02),
        xlims = (0, 1050),
        label = "",
        size = (460, 300),
        left_margin = 5Plots.mm,
        bottom_margin = 5Plots.mm,
        top_margin = 5Plots.mm,
        right_margin = 3Plots.mm,
    )
    annotate!(500, 0.92, Plots.text("(b) Full model", 9, :center))

    p_combined = plot(
        p1, p2,
        layout = (1, 2),
        size = (900, 340),
        left_margin = 5Plots.mm,
        bottom_margin = 8Plots.mm,
    )

    savefig_both(p_combined, "fig4_policy_functions")
    return p_combined
end


# =====================================================================
# Figure 5: CEV Heatmap
# =====================================================================
function figure_5_cev_heatmap()
    println("Generating Figure 5: CEV Heatmap...")

    csv_path = joinpath(@__DIR__, "..", "tables", "csv", "welfare_cev_grid.csv")
    raw = readdlm(csv_path, ',', Any; skipstart=1)

    # Extract "No bequest" CEV column (column 3)
    wealth_vals = Float64[]
    health_labels_raw = String[]
    cev_vals = Float64[]

    for i in 1:size(raw, 1)
        push!(wealth_vals, Float64(raw[i, 1]))
        push!(health_labels_raw, strip(string(raw[i, 2])))
        push!(cev_vals, Float64(raw[i, 3]))  # cev_No_bequest
    end

    # Unique wealth and health values
    unique_wealth = unique(wealth_vals)
    unique_health = unique(health_labels_raw)  # ["Good", "Fair", "Poor"]
    nW = length(unique_wealth)
    nH = length(unique_health)

    # Build matrix: rows = health (reversed for display: Poor at top), cols = wealth
    cev_matrix = zeros(nH, nW)
    for i in eachindex(wealth_vals)
        iw = findfirst(==(wealth_vals[i]), unique_wealth)
        ih = findfirst(==(health_labels_raw[i]), unique_health)
        cev_matrix[ih, iw] = cev_vals[i] * 100  # convert to percent
    end

    # Reverse health ordering so Good is at top
    cev_display = cev_matrix[end:-1:1, :]
    health_display = reverse(unique_health)

    # Wealth labels in $K or $M
    function wealth_label(w)
        if w >= 1_000_000
            return @sprintf("\$%.0fM", w / 1_000_000)
        else
            return @sprintf("\$%dK", round(Int, w / 1000))
        end
    end
    w_labels = [wealth_label(w) for w in unique_wealth]

    p = heatmap(
        1:nW, 1:nH, cev_display,
        color = cgrad([:white, CB_CYAN, CB_BLUE], [0.0, 0.3, 1.0]),
        clims = (0, maximum(cev_display) * 1.05),
        xticks = (1:nW, w_labels),
        yticks = (1:nH, health_display),
        xlabel = "Initial Wealth",
        ylabel = "Health at Age 65",
        colorbar_title = "CEV (%)",
        size = (560, 280),
        left_margin = 5Plots.mm,
        bottom_margin = 8Plots.mm,
        top_margin = 3Plots.mm,
        right_margin = 8Plots.mm,
        xrotation = 30,
    )

    # Annotate cells with values
    for ih in 1:nH
        for iw in 1:nW
            val = cev_display[ih, iw]
            txt = val < 0.001 ? "0" : @sprintf("%.2f", val)
            txt_color = val > maximum(cev_display) * 0.5 ? :white : :black
            annotate!(iw, ih, Plots.text(txt, 8, txt_color, :center))
        end
    end

    savefig_both(p, "fig5_cev_heatmap")
    return p
end

# =====================================================================
# Main
# =====================================================================
function main()
    println("=" ^ 60)
    println("  FIGURE GENERATION")
    println("  Quantifying the Annuity Puzzle")
    println("=" ^ 60)
    println()

    figure_1_decomposition()
    println()

    figure_2_gamma_sensitivity()
    println()

    figure_3_hazard_sensitivity()
    println()

    figure_4_policy_functions()
    println()

    figure_5_cev_heatmap()
    println()

    println("=" ^ 60)
    println("  All figures saved to:")
    println("    PDF: $FIG_PDF")
    println("    PNG: $FIG_PNG")
    println("=" ^ 60)
end

main()
